name: Multi-Environment Deployment

on:
  workflow_dispatch:  # Manual trigger

jobs:
  dev-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - run: echo "Deploying to DEV environment"
      - run: echo "Simulated deployment steps..."
      - uses: actions/upload-artifact@v4
        with:
          name: dev-deploy-log
          path: /tmp/deploy.log

  staging-deploy:
    needs: dev-deploy
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - run: echo "Deploying to STAGING (requires approval)"
      - run: echo "Simulated staging deployment..."

  production-deploy:
    needs: staging-deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo "Deploying to PRODUCTION (requires approval)"
      - run: echo "Simulated production deployment..."
