name: Full CI/CD with Environments

on:
  workflow_dispatch:

jobs:
  development:
    name: Development Lint & Simulate Deploy
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm init -y
          npm install stylelint stylelint-config-standard htmlhint --save-dev

      - name: Run stylelint
        run: |
          npx stylelint "styles/**/*.css" > stylelint-dev.txt || echo "stylelint errors ignored"

      - name: Run htmlhint
        run: |
          npx htmlhint "src/**/*.html" > htmlhint-dev.txt || echo "htmlhint errors ignored"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lint-dev
          path: |
            stylelint-dev.txt
            htmlhint-dev.txt

      - name: Use secret
        run: echo "Dev API Key: ${{ secrets.API_KEY }}"

      - name: Simulated Deploy
        run: echo "Deployed to DEVELOPMENT"

  staging:
    name: Staging Lint & Simulate Deploy
    runs-on: ubuntu-latest
    needs: development
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm init -y
          npm install stylelint stylelint-config-standard htmlhint --save-dev

      - name: Run stylelint
        run: |
          npx stylelint "styles/**/*.css" > stylelint-staging.txt || echo "stylelint errors ignored"

      - name: Run htmlhint
        run: |
          npx htmlhint "src/**/*.html" > htmlhint-staging.txt || echo "htmlhint errors ignored"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lint-staging
          path: |
            stylelint-staging.txt
            htmlhint-staging.txt

      - name: Use secret
        run: echo "Staging API Key: ${{ secrets.API_KEY }}"

      - name: Simulated Deploy
        run: echo "Deployed to STAGING"

  production:
    name: Production Lint & Simulate Deploy
    runs-on: ubuntu-latest
    needs: staging
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm init -y
          npm install stylelint stylelint-config-standard htmlhint --save-dev

      - name: Run stylelint
        run: |
          npx stylelint "styles/**/*.css" > stylelint-prod.txt || echo "stylelint errors ignored"

      - name: Run htmlhint
        run: |
          npx htmlhint "src/**/*.html" > htmlhint-prod.txt || echo "htmlhint errors ignored"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lint-production
          path: |
            stylelint-prod.txt
            htmlhint-prod.txt

      - name: Use secret
        run: echo "Production API Key: ${{ secrets.API_KEY }}"

      - name: Simulated Deploy
        run: echo "Deployed to PRODUCTION"
